### PR TITLE
Revert "Merge branch 'main' into main"

### PR DESCRIPTION
**Pull request by TheMowgliMan**
This reverts commit 0311b27eae1600028886e469983c76f2681c5260, reversing
changes made to 760fa85802886f2ac7d82a47e96fd1c3fcbb25b2.

AND IT FIXES SOMETHING THAT ALMOST KILLED THIS! WE SUCCESSFULLY PERFORMED ARTIFICIAL RESUSITATION (for code).

### CODE REVIEW

**Comment by 3quarterscolon** [comment]
yay™

**Comment by TheMowgliMan** [comment]
lolz

**Comment by TheMowgliMan** [comment]
You wanna know what, I think we killed this repo... I think we need to start working on your fix-it repo. It'll be fine.

**Comment by TheMowgliMan** [comment]
I'm gonna delete everything on the main repo, and then refill it with fix-it.

**Comment by TheMowgliMan** [comment]
Worked!

**Pull request merged**
